apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shared-storage-example.fullname" . }}-shared-pvc
  labels:
    {{- include "shared-storage-example.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}